### ISSUE TITLE
Feature request: Whatsapp Channel

### ISSUE THREAD

**Issue by digitall-it** [botpress/v12#382]
The next big thing is the new WhatsApp Business API, just announced today:

https://www.whatsapp.com/business/api

as it is one of the biggest chat systems all over the world, and the number one in many countries, the ability to finally access an open API is something that really suits the spirit of Botpress.

Hereby, I kindly request consideration of the design of a new channel for WhatsApp.

**Comment by estebanrvcielum** [comment]
Hello. How are they? I see that they posted earlier that they managed to integrate a chatbot with WhatsApp, I was wondering if you could help me, I am currently using V12 in Docker and I want to do the integration with my company's WhatsApp APIs. All this so that it enters the flow if you talk to that WhatsApp line or if a template is sent through an API Business, when answering a specific button it enters the flow. Thank you very much, if possible you can contact me at estestrepo@omnivida. org If you have any manual or instructions that I should follow I would appreciate it.

**Comment by zhoucrance** [comment]
Hello. Any update for whatsApp API and community botpress integration. Any help will be very much appreciated.
